### ISSUE TITLE
Shelly Plus 1PM does not work

### ISSUE THREAD

**Issue by Vorta** [phiten/mgos32-to-tasmota32#14]
It does not seem to work with Shelly Plus 1PM. I tried flashing 4 of them with `http://ota.tasmota.com/tasmota32/shelly/mgos32-to-tasmota32-Plus1PM.zip` and all 4 were dead after they installed the firmware. No lights or WiFi networks - completely dead.

Flashing them via serial brought them back to life.

**Comment by phiten** [comment]
That is very weird. I have flashed quite a lot Plus 1PM without problem.

The firmware update actually was developed on a Plus 1PM so it was tested quite thoroughly.

Which mongoose os version was on the Shelly when you tried the conversion?

Did you check as stated in step 5. if the Shelly came back with mongoose os and directly connected to your wifi again? If this happens you just need to run the update again.
This happens due to the bootloader booting into the wrong app partition as we overwrite it as well as the partitions.

**Comment by anonymous-one** [comment]
I will throw in my 2 cents...

Same thing here. Just flashed one Plus1PM and it got bricked :(

Shelly firmware was version 0.13.0.

I verified it was not on the old OS... I actually spent about 30 minutes on it trying various resets etc using the on-device button etc etc... Nothing.

Edit :

For what its worth... I just updated a PLUS2PM with 0.14.1 stock and no issues what so ever. So whatever this is, its PLUS1PM specific.

**Comment by anonymous-one** [comment]
Hate to be a pain in the butt, anything I can do to help resolve this?

I'm reaching the end of converting my about 40 shelly devices from mgos/mgos32 to tasmota and have about 5 of these PLUS1PM left... They are of course in wall so doing a serial update is a pain.

I was thinking about downgrading one to 0.12.0 and seeing how that goes.... But I see with gen2 devices the firmware is not available for download (easily?)?

Edit : For kicks I just tried using one of the older builds in this repo (12.4 I believe), and the same thing happened. After the OTA update it disconnected from my current wifi network and did not start to advertise the tasmota AP. This device has mgos32 0.13.0.

**Comment by phiten** [comment]
Just got in two new Plus 1PM and I will have a look at it in the next few days.

**Comment by phiten** [comment]
I'm very sorry but I can't confirm this. I just tried it on two different Plus 1PM from two different orders.

I updated both to mgos32 0.14.1 (latest stable) and then applied the OTA update and besides the documented wrong boot to mgos32 again (reapply update see documentation) it works perfectly fine.

Please try it with the latest stable mgos32 Update again. I can't do anything else right now.

**Comment by Qowy** [comment]
I had the same problem. Flash would reboot to shelly again (0.14.1) and I could not flash tasmota again, since it would immediatly fail with an error message (something went wrong...)
Now after a few weeks running under Shelly there was an update to 1.0.2 beta.
I did this and instead of updating it now rebooted into the tasmota I flashed weeks before.
Weird...

**Comment by Klaus3d3** [comment]
Sadly the same here. Already bricked 3 plus1 and 1 plus1pm.
